"""Mudando o tipo dos campos

Revision ID: 91c3c68d1be5
Revises: c38e5d987a1f
Create Date: 2025-01-23 12:19:15.036698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91c3c68d1be5'
down_revision: Union[str, None] = 'c38e5d987a1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
